name: logic_rdv_v0
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  #sdk: ">=2.16.0 <3.0.0"
  #flutter: ">=2.10.0"
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"
  #sdk: ">=2.19.6 <3.0.0"
  #flutter: ">=3.7.10"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.0
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: ^2.0.0
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  json_annotation: ^4.6.0
  #  location: ^3.0.0
  material_design_icons_flutter: ^7.0.7296
  rflutter_alert: ^2.0.2
  universal_io: ^2.0.3
  url_launcher: ^6.0.3
  line_awesome_flutter: ^2.0.0
  geolocator: ^10.1.0
  diacritic: ^0.1.3
  flutter_downloader: ^1.6.0
  google_fonts: ^6.1.0
  flutter_dash: ^1.0.0
  textfield_search: ^0.10.0
  easy_debounce: ^2.0.0

  flutter_credit_card: ^4.0.1

  flutter_phone_direct_caller: ^2.0.0

  timezone: ^0.9.2

  font_awesome_flutter: ^10.6.0
  #screen: ^0.0.5
  launch_review: ^3.0.1
  wakelock: ^0.6.1
  wonderpush_flutter: ^2.0.2
  wonderpush_fcm_flutter: ^1.0.1
  shared_preferences: ^2.0.15
  permission_handler: ^11.0.0
  #  flutter_stripe: ^2.0.2
  image_picker: ^1.0.5
  flutter_stripe: ^10.0.0
  #screen: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  built_collection: ^5.0.0
  built_value: ^8.0.4
  built_value_generator: ^8.0.4

  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.3.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    #Images
    - assets/images/
    #Gif
    - assets/gif/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-SemiBold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
